import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar, generated from the docs/ folder. Order comes from each page's
// `sidebar_position` front matter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
